"use client";

import Link from "next/link";
import { ArrowRight, Check, Code2, FileCheck2, ShieldCheck, Users } from "lucide-react";
import { useAuth } from "@/lib/auth/AuthContext";
import { useRouter } from "next/navigation";
import { logFunnelEvent } from "@/lib/analytics/logEvent";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";

export default function HomePage() {
  const { user, role } = useAuth(); const router = useRouter();
  const go = (target: "candidate" | "employer") => { logFunnelEvent("landing_cta_clicked", { role: target }); router.push(user && role ? role === "candidate" ? "/candidate/profile" : "/employer/dashboard" : "/signup"); };
  return <div>
    <section className="border-b bg-card"><div className="mx-auto grid max-w-7xl gap-14 px-5 py-16 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-28">
      <div className="animate-enter"><Badge variant="verified"><ShieldCheck data-icon="inline-start" /> Proof-first hiring</Badge><h1 className="mt-6 max-w-3xl text-balance text-4xl font-semibold tracking-[-0.04em] text-foreground sm:text-6xl">Proof of skill beats college pedigree.</h1><p className="mt-6 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">Meritlane helps engineers show what they can build and gives employers evidence they can evaluate before they hire.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button size="lg" onClick={() => go("candidate")}>Prove your skills <ArrowRight data-icon="inline-end" /></Button><Button size="lg" variant="outline" onClick={() => go("employer")}>Hire with proof</Button></div><p className="mt-5 text-xs text-muted-foreground">Built for ambitious early-career engineers and teams that value signal.</p></div>
      <div className="animate-enter rounded-lg border bg-background p-4 shadow-sm [animation-delay:120ms]"><div className="flex items-center justify-between border-b pb-4"><div><p className="font-mono text-[11px] uppercase tracking-[0.16em] text-muted-foreground">Example / Preview</p><p className="mt-1 font-semibold">Verified candidate record</p></div><Badge variant="verified">Active</Badge></div><div className="grid gap-3 py-5 sm:grid-cols-2"><div className="rounded-md border bg-card p-4"><div className="flex items-center gap-2 text-sm font-medium"><span className="size-2 rounded-full bg-emerald-500" /> Verification status</div><p className="mt-3 text-2xl font-semibold">Verified</p><p className="mt-1 text-xs text-muted-foreground">Technical assessment passed</p></div><div className="rounded-md border bg-card p-4"><p className="text-xs text-muted-foreground">Core signal</p><p className="mt-2 font-semibold">Backend Engineering</p><div className="mt-4 flex flex-wrap gap-1.5"><Badge>Python</Badge><Badge>APIs</Badge><Badge>SQL</Badge></div></div></div><div className="border-t pt-4 text-xs text-muted-foreground">Evidence is reviewed as a record of ability—not a proxy for pedigree.</div></div>
    </div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="max-w-2xl"><p className="font-mono text-xs uppercase tracking-[0.16em] text-primary">The gap</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">A resume tells you what someone claims. Proof shows you what they can do.</h2><p className="mt-5 leading-7 text-muted-foreground">Hiring teams often use college brand as a shortcut because reliable evidence is hard to find. Meritlane replaces that shortcut with a practical, reviewable proof stack.</p></div></section>
    <section id="model" className="border-y bg-card"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-primary">The model</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">From work to trusted signal.</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">A clear path for candidates. A concise record for hiring teams.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-lg border bg-border md:grid-cols-3">{[[Code2,"Build your proof","Submit projects and repositories that show how you think and build."],[FileCheck2,"Verify your skills","Complete a secure technical assessment tied to a specific skill signal."],[Users,"Get discovered","Give employers a better starting point than a keyword filter."]].map(([Icon,title,desc]) => <div key={title as string} className="bg-card p-6"><Icon className="text-primary" aria-hidden="true" /><h3 className="mt-8 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{desc as string}</p></div>)}</div></div></section>
    <section id="employers" className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-2 lg:px-8 lg:py-24"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-primary">For employers</p><h2 className="mt-4 text-3xl font-semibold tracking-tight">Evaluate evidence before pedigree.</h2><p className="mt-5 leading-7 text-muted-foreground">See the work, verification state, and core skills that make an engineer worth a closer look. Meritlane is designed to make the first review more grounded.</p><ul className="mt-8 flex flex-col gap-4 text-sm">{["Technical assessment status","Project and repository evidence","Structured skill signals"].map(item => <li key={item} className="flex items-center gap-3"><Check className="text-primary" aria-hidden="true" />{item}</li>)}</ul></div><div className="rounded-lg bg-primary p-8 text-primary-foreground"><p className="font-mono text-xs uppercase tracking-[0.16em] text-primary-foreground/70">Verification</p><h3 className="mt-5 text-2xl font-semibold">A status with a clear meaning.</h3><p className="mt-4 leading-7 text-primary-foreground/80">Verified means a candidate completed Meritlane&apos;s secure assessment for a specific skill. It is a practical credential—not a guarantee, and not a college proxy.</p><Button className="mt-8 bg-card text-primary hover:bg-secondary" onClick={() => go("employer")}>Explore hiring workspace <ArrowRight data-icon="inline-end" /></Button></div></section>
    <section className="border-t bg-secondary"><div className="mx-auto flex max-w-4xl flex-col items-center px-5 py-16 text-center lg:py-24"><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">Your next hire should be based on what they can do.</h2><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" onClick={() => go("candidate")}>Build your proof</Button><Button size="lg" variant="outline" onClick={() => go("employer")}>Find verified talent</Button></div></div></section>
  </div>;
}
